export {default as Dashboard} from './Dashboard/Dashboard'
export {default as Error} from './Error/Error'
export {default as Home} from './Home/Home'
export {default as SignIn} from './SignIn/SignIn'
export {default as SignUp} from './SignUp/SignUp'
